apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
spec:
  #replicas: {{ .Values.replicaCount }}
  replicas: 5
  selector:
    matchLabels:
      {{- include "test-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.service.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
